version: '3.8'
services:
  # flask-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - postgres-db
  #   environment:
  #     - FLASK_APP=server.py
  #     - FLASK_RUN_HOST=0.0.0.0
  #     - FLASK_RUN_PORT=5000
  #     - SQLALCHEMY_DATABASE_URI=postgresql://ash:password@postgres-db:5432/aladdin
  #     - ENV=production
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - app-network

  postgres-db:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_USER: ash
      POSTGRES_PASSWORD: pokemon
      POSTGRES_DB: aladdin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local
networks:
  app-network:
    driver: bridge
